#!/bin/sh

# Steven Black
src1='https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts'

# Dan Pollock
src2='https://someonewhocares.org/hosts/zero/'

# MVPS hosts
src3='https://winhelp2002.mvps.org/hosts.txt'

# My file with shitty Czech news sites
src4='https://raw.githubusercontent.com/tomaskala/dotfiles/master/.local/share/dns-blacklist'

# NoCoin filter
src5='https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt'

/usr/bin/curl "${src1}" "${src2}" "${src3}" "${src4}" "${src5}" \
  | /usr/bin/awk '$1 == "0.0.0.0" && $2 != "0.0.0.0" {print $2}' \
  | /usr/bin/tr -d '\r' \
  | /usr/bin/tr '[:upper:]' '[:lower:]' \
  | /usr/bin/sort \
  | /usr/bin/uniq \
  | /usr/bin/sort \
  | /usr/bin/awk '{print "local-zone: \""$1".\" redirect\nlocal-data: \""$1". A 0.0.0.0\""}'
